import { initializeApp, getApps, getApp } from "https://www.gstatic.com/firebasejs/10.8.1/firebase-app.js";
import { getAuth, signOut } from "https://www.gstatic.com/firebasejs/10.8.1/firebase-auth.js";
import { getFirestore, collection, query, onSnapshot, doc, setDoc, updateDoc, addDoc, serverTimestamp, orderBy, where, getDocs, limit } from "https://www.gstatic.com/firebasejs/10.8.1/firebase-firestore.js";
import { getStorage, ref, uploadBytes, getDownloadURL } from "https://www.gstatic.com/firebasejs/10.8.1/firebase-storage.js";

const firebaseConfig = {
  apiKey: "AIzaSyBtDMYBR0jcyK-JfgsYtET1SenPngzmQi4",
  authDomain: "mwamini-chatting-web.firebaseapp.com",
  databaseURL: "https://mwamini-chatting-web-default-rtdb.firebaseio.com",
  projectId: "mwamini-chatting-web",
  storageBucket: "mwamini-chatting-web.firebasestorage.app",
  messagingSenderId: "640958885512",
  appId: "1:640958885512:web:2f9a636acc85534009b93d",
  measurementId: "G-SW9FBXX78G"
};

const app = getApps().length === 0 ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
const db = getFirestore(app);
const storage = getStorage(app);

let currentUser = null; 
let activeChatId = null;
let unsubscribeMessages = null;
let activeSessionStartTime = null; 

let audioMediaRecorder = null;
let recordedAudioChunks = [];
const trackedUnreadNotificationSet = new Set();

function initDashboardPage() {
    if (!document.getElementById("users-container") && !document.getElementById("message-form")) {
        console.log("Welcome view active. Core engines operating cleanly.");
        return; 
    }

    const savedUid = localStorage.getItem("session_uid");
    const savedName = localStorage.getItem("session_name");

    if (!savedUid) {
        window.location.href = "index.html";
        return; 
    }

    currentUser = { uid: savedUid, name: savedName, accountMode: "standard" };
    updateDoc(doc(db, "users", currentUser.uid), { isOnline: true }).catch(() => {});

    // Live monitor status updates on current user account profile
    onSnapshot(doc(db, "users", currentUser.uid), (docSnap) => {
        if (docSnap.exists()) {
            const data = docSnap.data();
            if(document.getElementById("current-user-title")) document.getElementById("current-user-title").innerText = data.name;
            if(document.getElementById("my-status-display")) document.getElementById("my-status-display").innerText = data.status || "Available";
        }
    });

    // --- CUSTOM DISPLAY ROOM CHAT WALLPAPER ENGINE ---
    const backgroundSelector = document.getElementById("background-changer");
    if (backgroundSelector) {
        backgroundSelector.addEventListener("change", (e) => {
            const chosenColorHex = e.target.value;
            const messageLayoutCanvas = document.getElementById("message-stream");
            if (messageLayoutCanvas) {
                messageLayoutCanvas.style.backgroundColor = chosenColorHex;
                messageLayoutCanvas.style.color = (chosenColorHex === "#121b22") ? "#ffffff" : "#000000";
            }
        });
    }

    // --- SYSTEM ROOM CREATION PIPELINE DESIGN ---
    const groupSelectMenu = document.getElementById("group-type-select");
    const groupPasswordField = document.getElementById("group-password-input");
    const createGroupActionBtn = document.getElementById("create-group-btn");

    if (groupSelectMenu && groupPasswordField) {
        groupSelectMenu.addEventListener("change", (e) => {
            if (e.target.value === "protected") {
                groupPasswordField.classList.remove("hidden");
            } else {
                groupPasswordField.classList.add("hidden");
            }
        });
    }

    if (createGroupActionBtn) {
        createGroupActionBtn.addEventListener("click", async () => {
            const groupNameInput = document.getElementById("group-name-input");
            const title = groupNameInput ? groupNameInput.value.trim() : "";
            const architectureType = groupSelectMenu ? groupSelectMenu.value : "public";
            const codeKeyPayload = groupPasswordField ? groupPasswordField.value.trim() : "";

            if (!title) {
                alert("Please declare an assignment name label for your room.");
                return;
            }
            if (architectureType === "protected" && !codeKeyPayload) {
                alert("Protected channels require a password validation token asset.");
                return;
            }

            try {
                const autoGeneratedRoomKey = "ROOM_" + Date.now();
                await setDoc(doc(db, "users", autoGeneratedRoomKey), {
                    uid: autoGeneratedRoomKey,
                    name: `[ROOM] ${title}`,
                    status: `Open Global Channel (${architectureType.toUpperCase()})`,
                    isGroup: true,
                    groupType: architectureType,
                    groupPassword: codeKeyPayload,
                    isOnline: true
                });

                alert(`Global Chat Room "${title}" created successfully! It is now permanently visible to all members.`);
                if(groupNameInput) groupNameInput.value = "";
                if(groupPasswordField) groupPasswordField.value = "";
                executeTargetSearchQuery(""); // Refresh sidebar instantly
            } catch (err) {
                alert("Room composition failure: " + err.message);
            }
        });
    }

    // --- REALTIME ACTIVE UNREAD MESSAGE TRAFFIC CONTROLLER ---
    onSnapshot(collection(db, "chats"), (snapshot) => {
        snapshot.forEach((chatDoc) => {
            const info = chatDoc.data();
            if (chatDoc.id.startsWith("ROOM_") || (info.participants && info.participants.includes(currentUser.uid))) {
                onSnapshot(query(collection(db, "chats", chatDoc.id, "messages"), orderBy("createdAt", "desc"), limit(1)), (lastMessageSnapshot) => {
                    lastMessageSnapshot.forEach((mDoc) => {
                        const packet = mDoc.data();
                        if (packet.senderId !== currentUser.uid && chatDoc.id !== activeChatId) {
                            trackedUnreadNotificationSet.add(chatDoc.id);
                            renderSidebarUnreadAlertBadge(chatDoc.id);
                        }
                    });
                });
            }
        });
    });

    // --- STATUS STORIES ENGINE ---
    const updateStatusBtn = document.getElementById("update-status-btn");
    if (updateStatusBtn) {
        updateStatusBtn.addEventListener("click", async () => {
            const input = document.getElementById("status-input");
            const mediaInput = document.getElementById("status-media-file");
            const textPayload = input ? input.value.trim() : "";
            const attachedFile = mediaInput ? mediaInput.files[0] : null;

            if (!textPayload && !attachedFile) return;
            let downloadedMediaUrl = "";
            let computedMediaType = "text";

            try {
                if (attachedFile) {
                    computedMediaType = attachedFile.type.startsWith("video/") ? "video" : "image";
                    const storageLocationRef = ref(storage, `mwamini_statuses/${currentUser.uid}/${Date.now()}_${attachedFile.name}`);
                    const snapshot = await uploadBytes(storageLocationRef, attachedFile);
                    downloadedMediaUrl = await getDownloadURL(snapshot.ref);
                }

                await addDoc(collection(db, "statuses"), {
                    uid: currentUser.uid,
                    userName: currentUser.name,
                    accountMode: "standard",
                    textPayload: textPayload || `Posted an update status ${computedMediaType}`,
                    mediaUrl: downloadedMediaUrl,
                    statusType: computedMediaType,
                    createdAt: serverTimestamp()
                });

                await updateDoc(doc(db, "users", currentUser.uid), { status: textPayload || "Active with a status update." });
                if(input) input.value = "";
                if(mediaInput) mediaInput.value = "";
                alert("Status update posted successfully.");
            } catch (err) {
                alert("Status upload failed: " + err.message);
            }
        });
    }

    const retentionThreshold = new Date(Date.now() - 24 * 60 * 60 * 1000);
    onSnapshot(query(collection(db, "statuses"), orderBy("createdAt", "desc"), limit(20)), (snapshot) => {
        const feedContainerTray = document.getElementById("active-statuses-view");
        if (!feedContainerTray) return;
        feedContainerTray.innerHTML = "";

        snapshot.forEach((statusDoc) => {
            const data = statusDoc.data();
            if (!data.createdAt) return;
            if (data.createdAt.toDate() > retentionThreshold) {
                const layoutBubble = document.createElement("div");
                layoutBubble.style = "background: #e1f5fe; border: 1px solid #b3e5fc; padding: 6px 12px; border-radius: 12px; font-size: 12px; color: #01579b; cursor: pointer; display: flex; flex-direction: column; gap: 4px; white-space:nowrap;";
                
                let embeddedMediaOutputElement = "";
                if (data.statusType === "image") {
                    embeddedMediaOutputElement = `<img src="${data.mediaUrl}" style="width:50px; height:50px; object-fit:cover; border-radius:4px;">`;
                } else if (data.statusType === "video") {
                    embeddedMediaOutputElement = `<video src="${data.mediaUrl}" style="width:50px; height:50px; object-fit:cover; border-radius:4px;" muted></video>`;
                }

                layoutBubble.innerHTML = `<strong>${data.userName}</strong><span>${data.textPayload}</span>${embeddedMediaOutputElement}`;
                if (data.mediaUrl) {
                    layoutBubble.addEventListener("click", () => window.open(data.mediaUrl, "_blank"));
                }
                feedContainerTray.appendChild(layoutBubble);
            }
        });
    });

    // --- AUDIO MEMO RECORDER RECORDINGS ---
    const recordVoiceBtn = document.getElementById("voice-record-btn");
    const recordStatusText = document.getElementById("voice-recording-status");

    if (recordVoiceBtn) {
        recordVoiceBtn.addEventListener("click", async () => {
            if (!activeChatId) return;
            if (!audioMediaRecorder) {
                try {
                    const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
                    audioMediaRecorder = new MediaRecorder(stream);
                    audioMediaRecorder.ondataavailable = (e) => { if (e.data.size > 0) recordedAudioChunks.push(e.data); };
                    audioMediaRecorder.onstop = async () => {
                        const audioBlob = new Blob(recordedAudioChunks, { type: "audio/ogg; codecs=opus" });
                        recordedAudioChunks = [];
                        if(recordStatusText) recordStatusText.classList.add("hidden");
                        recordVoiceBtn.style.color = "initial";

                        const voiceStorageRef = ref(storage, `voice_memos/${activeChatId}/${Date.now()}_clip.ogg`);
                        const snap = await uploadBytes(voiceStorageRef, audioBlob);
                        const downloadUrl = await getDownloadURL(snap.ref);

                        await addDoc(collection(db, "chats", activeChatId, "messages"), {
                            text: "Voice Note Transmission",
                            fileUrl: downloadUrl,
                            type: "audio",
                            senderId: currentUser.uid,
                            senderName: currentUser.name,
                            createdAt: serverTimestamp()
                        });
                    };
                } catch (err) {
                    alert("Audio device access denied: " + err.message);
                    return;
                }
            }

            if (audioMediaRecorder.state === "inactive") {
                audioMediaRecorder.start();
                if(recordStatusText) recordStatusText.classList.remove("hidden");
                recordVoiceBtn.style.color = "#ea0038";
            } else {
                audioMediaRecorder.stop();
            }
        });
    }

    // --- SEARCH BAR LOOKUP AND DIRECTORY FEED ACTION ---
    const searchField = document.getElementById("search-users");
    if (searchField) {
        searchField.addEventListener("input", (e) => executeTargetSearchQuery(e.target.value.trim()));
    }
    executeTargetSearchQuery(""); // Fire core initial visibility sequence out of the box

    // --- MESSAGE FORM POST SUBMISSIONS ---
    const messageForm = document.getElementById("message-form");
    if (messageForm) {
        messageForm.addEventListener("submit", async (e) => {
            e.preventDefault();
            const input = document.getElementById("message-input");
            if (!input || !input.value.trim() || !activeChatId) return;

            const text = input.value.trim();
            input.value = "";

            await addDoc(collection(db, "chats", activeChatId, "messages"), {
                text: text,
                type: "text",
                senderId: currentUser.uid,
                senderName: currentUser.name,
                createdAt: serverTimestamp()
            });
        });
    }

    const logoutBtn = document.getElementById("logout-btn");
    if (logoutBtn) {
        logoutBtn.addEventListener("click", async () => {
            await updateDoc(doc(db, "users", currentUser.uid), { isOnline: false }).catch(() => {});
            localStorage.clear();
            signOut(auth).finally(() => { window.location.href = "index.html"; });
        });
    }
}

async function executeTargetSearchQuery(keyword) {
    const listCanvas = document.getElementById("users-container");
    if (!listCanvas) return;
    listCanvas.innerHTML = "";

    // PERMANENT VISIBILITY RULE IMPLEMENTED:
    // If the user hasn't typed anything, fetch and permanently show ALL created public and protected chat groups automatically.
    if (!keyword) {
        const globalGroupsSnap = await getDocs(query(collection(db, "users"), where("isGroup", "==", true)));
        if(globalGroupsSnap.empty) {
            listCanvas.innerHTML = `<p style="font-size:12px; color:#667781; text-align:center; padding:20px; margin:0;">No active group rooms exist. Build a room above to launch a global channel thread.</p>`;
            return;
        }
        globalGroupsSnap.forEach((doc) => buildSidebarChannelRowElement(doc.data()));
        return;
    }

    // Otherwise, parse direct matched key phrases to load users or targeted chat titles
    const standardKeywordSnap = await getDocs(query(collection(db, "users"), where("name", "==", keyword)));
    if (standardKeywordSnap.empty) {
        listCanvas.innerHTML = `<p style="font-size:12px; color:#ea0038; text-align:center; padding:20px; margin:0;">No registered users or groups found matching that name sequence.</p>`;
        return;
    }

    standardKeywordSnap.forEach((userDoc) => {
        const data = userDoc.data();
        if (data.uid !== currentUser.uid) {
            buildSidebarChannelRowElement(data);
        }
    });
}

function buildSidebarChannelRowElement(userData) {
    const canvas = document.getElementById("users-container");
    const rowElement = document.createElement("div");
    rowElement.style = "display:flex; align-items:center; justify-content:space-between; padding:12px 16px; cursor:pointer; border-bottom:1px solid #f8f9fa; transition: background 0.1s;";
    rowElement.onmouseenter = () => rowElement.style.backgroundColor = "#f0f2f5";
    rowElement.onmouseleave = () => rowElement.style.backgroundColor = "transparent";

    const isRoomChannel = userData.isGroup === true;
    
    // Assign structural indicator badges depending on privacy configurations
    let badgeClass = userData.isOnline ? "status-online" : "status-offline";
    let statusTextLabel = userData.isOnline ? "online" : "offline";

    if (isRoomChannel) {
        badgeClass = (userData.groupType === "protected") ? "status-protected" : "status-public";
        statusTextLabel = (userData.groupType === "protected") ? "🔒 Protected" : "🌐 Public";
    }

    rowElement.innerHTML = `
        <div style="display:flex; align-items:center; gap:12px; flex:1; min-width:0;">
            <div style="background:${isRoomChannel ? '#008069' : '#00a884'}; color:white; width:44px; height:44px; border-radius:50%; display:flex; align-items:center; justify-content:center; font-weight:bold; font-size:18px; flex-shrink:0;">
                ${isRoomChannel ? '👥' : userData.name.charAt(0).toUpperCase()}
            </div>
            <div style="flex:1; min-width:0;">
                <h4 style="margin:0; font-size:14.5px; color:#111b21; font-weight:600; display:flex; align-items:center;">
                    <span style="white-space:nowrap; overflow:hidden; text-overflow:ellipsis; max-width:160px;">${userData.name}</span>
                    <span class="status-badge ${badgeClass}">${statusTextLabel}</span>
                </h4>
                <p style="margin:2px 0 0 0; font-size:12.5px; color:#667781; white-space:nowrap; overflow:hidden; text-overflow:ellipsis;">${userData.status || 'Available'}</p>
            </div>
        </div>
        <div id="badge-holder-${userData.uid}" style="flex-shrink:0; padding-left:10px;"></div>
    `;

    rowElement.addEventListener("click", () => {
        // ENFORCE RUNTIME INTERACTIVE PASSWORD REQUEST CHALLENGE GATE
        if (isRoomChannel && userData.groupType === "protected") {
            const clientAttemptToken = prompt(`Security Verification required.\nEnter entry password code to access the channel thread "${userData.name}":`);
            if (clientAttemptToken !== userData.groupPassword) {
                alert("Authorization Denied: Invalid security channel password key.");
                return;
            }
        }

        activeChatId = userData.uid;
        activeSessionStartTime = new Date();

        // Expunge pending notification triggers
        trackedUnreadNotificationSet.delete(activeChatId);
        const dynamicAlertWidgetRef = document.getElementById(`badge-holder-${userData.uid}`);
        if(dynamicAlertWidgetRef) dynamicAlertWidgetRef.innerHTML = "";

        document.getElementById("no-chat-selected").classList.add("hidden");
        document.getElementById("active-chat-area").classList.remove("hidden");
        document.getElementById("chat-header-name").innerText = userData.name;

        const presenceBadge = document.getElementById("chat-header-presence-badge");
        if(presenceBadge) {
            presenceBadge.className = `status-badge ${badgeClass}`;
            presenceBadge.innerText = statusTextLabel;
        }

        setDoc(doc(db, "chats", activeChatId), {
            chatId: activeChatId,
            participants: isRoomChannel ? [currentUser.uid] : [currentUser.uid, userData.uid],
            updatedAt: serverTimestamp()
        }, { merge: true });

        bindLiveIsolatedMessageStreams(collection(db, "chats", activeChatId, "messages"));
    });

    if(canvas) {
        canvas.appendChild(rowElement);
        if (trackedUnreadNotificationSet.has(userData.uid)) {
            renderSidebarUnreadAlertBadge(userData.uid);
        }
    }
}

function renderSidebarUnreadAlertBadge(targetKeyId) {
    const targetElementRef = document.getElementById(`badge-holder-${targetKeyId}`);
    if (targetElementRef) {
        targetElementRef.innerHTML = `<span class="unread-indicator">NEW</span>`;
    }
}

function bindLiveIsolatedMessageStreams(collectionReference) {
    if (unsubscribeMessages) unsubscribeMessages();
    unsubscribeMessages = onSnapshot(query(collectionReference, orderBy("createdAt", "asc")), (snapshot) => {
        const chatBoxWindow = document.getElementById("message-stream");
        if (!chatBoxWindow) return;
        chatBoxWindow.innerHTML = "";

        snapshot.forEach((msgDoc) => {
            const data = msgDoc.data();
            if (!data.createdAt) return;

            if (data.createdAt.toDate() >= activeSessionStartTime) {
                const bubbleRow = document.createElement("div");
                const isMe = data.senderId === currentUser.uid;
                bubbleRow.style = `display:flex; justify-content:${isMe ? 'flex-end' : 'flex-start'}; margin-bottom:12px;`;
                
                let visualPayloadOutputBlock = "";
                if (data.type === "audio") {
                    visualPayloadOutputBlock = `<audio src="${data.fileUrl}" controls style="max-width:250px; outline:none;"></audio>`;
                } else {
                    visualPayloadOutputBlock = `
                        <div style="display:flex; justify-content:space-between; align-items:center; gap:25px; margin-bottom:3px;">
                            <span style="font-size:11px; font-weight:bold; color:#008069;">${data.senderName}</span>
                            <span class="read-aloud-bot" style="cursor:pointer; font-size:11px; font-weight:600; color:#00a884; background:rgba(0,168,132,0.08); padding:1px 5px; border-radius:4px;" title="Listen with Google Assistant">🔊 Speak</span>
                        </div>
                        <p style="margin:0; font-size:14px; white-space:pre-wrap; line-height:1.5; color:#111b21;">${data.text}</p>
                    `;
                }

                bubbleRow.innerHTML = `<div style="background:${isMe ? '#d9fdd3' : '#ffffff'}; padding:9px 14px; border-radius:10px; box-shadow:0 1px 2px rgba(0,0,0,0.06); max-width:68%; word-wrap:break-word;">${visualPayloadOutputBlock}</div>`;
                
                const cloudSpeakerBtn = bubbleRow.querySelector(".read-aloud-bot");
                if(cloudSpeakerBtn) {
                    cloudSpeakerBtn.addEventListener("click", () => {
                        const narrativeInstance = new SpeechSynthesisUtterance(data.text);
                        narrativeInstance.lang = 'en-US';
                        window.speechSynthesis.speak(narrativeInstance);
                    });
                }

                chatBoxWindow.appendChild(bubbleRow);
            }
        });
        chatBoxWindow.scrollTop = chatBoxWindow.scrollHeight;
    });
}

if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", initDashboardPage);
} else {
    initDashboardPage();
}
